name: doc_truyen_online_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  readmore: ^2.1.0
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  logger: ^2.0.2+1
  image_picker: ^1.0.6
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^9.0.0
  transparent_image: ^2.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
